# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momentum', '0015_auto_20160613_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='color',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
