# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('momentum', '0019_auto_20160615_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='last_completed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 15, 13, 22, 0, 611123, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='last_entry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 15, 13, 22, 0, 611078, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
