# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('momentum', '0020_auto_20160615_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='last_completed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 21, 13, 36, 18, 388461, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='last_entry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 21, 13, 36, 18, 388425, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=255),
        ),
    ]
