# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('momentum', '0021_auto_20160621_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='last_completed_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='last_entry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
